# Время игры в секундах (300 сек = 5 минут)
game-duration: 300

# Минимальное количество игроков для начала отсчета
min-number-of-players: 2

# Сюда плагин сам будет записывать координаты, если ты пропишешь /etm setspawn
# Но благодаря нашему хардкору, на плоской карте всё взлетит и без этого.
spawn:
  guard:
  prisoner:
cell:

# Список верстаков (если захочешь использовать ручную расстановку)
computers: []