name: EscapeTheMine
main: me.annie312.EscapeTheMine
version: 0.0.3
api-version: 1.12.2
author: Annie312

commands:
  etm:
    description: Побег из шахты — мультиарены
  lobby:
    description: Лобби (мир world)